version: "3.3"

services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      #log
      - "--log.level=DEBUG"
      #activate dashboard
      - "--api=true"
      - "--api.dashboard=true"
      #docker 
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"

      #https
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=thomas17.lips@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      #http
      - "--entrypoints.web.address=:80"
    labels:
      # enable traefik
      - "traefik.enable=true"
      #  redirect middleware
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      
      # global redirect to https
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
      
      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`traefik.tlips.be`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.middlewares.traefik-auth.basicauth.usersfile=/basic-auth-userfiles/traefik-dashboard"
      #default credentials for development 
      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$apr1$$36an5d0r$$8/7qf8N0toHNi6MHYNr5s."
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "$PWD/../Volumes/traefik/letsencrypt:/letsencrypt"
      - "$PWD/../Volumes/traefik/basic-auth-userfiles:/basic-auth-userfiles"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks: 
      - traefik
      - monitor

  whoami:
    image: "containous/whoami"
    labels:
      - "traefik.enable=true" 
      - "traefik.http.routers.whoami.rule=Host(`whoami.tlips.be`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
      #- "traefik.http.services.whoami.loadbalancer.server.port=80"

    networks:
      - traefik

     
networks:
  traefik:
    external: true
  monitor: 
    external: true
