version: "3.3"

services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      #log
      - "--log.level=DEBUG"
      #expose dashboard
      - "--api.insecure=true"
      #docker 
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"

      #https
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=thomas17.lips@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      #http
      - "--entrypoints.web.address=:80"
    labels:
      #  redirect middleware
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      
      # global redirect to https
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
      
      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`tlips.be`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=admin"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.middlewares.admin.basicauth.users=admin:dummy_password"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "$PWD/../Volumes/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks: 
      - traefik

  whoami:
    image: "containous/whoami"
    labels:
      - "traefik.enable=true" 
      - "traefik.http.routers.whoami.rule=Host(`whoami.tlips.be`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
      #- "traefik.http.services.whoami.loadbalancer.server.port=80"

    networks:
      - traefik

     
networks:
  traefik: {}
